services:
  database:
    image: redis:latest
    container_name: database
    networks:
      - app-network

  storage_api:
    build:
      context: ./service_b/app  
      dockerfile: Dockerfile
    container_name: storage_api
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=database
      - REDIS_PORT=6379
    depends_on:
      - database
    networks:
      - app-network

  resolution_api:
    build:
      context: ./service_a/app 
      dockerfile: Dockerfile
    container_name: resolution_api
    ports:
      - "8000:8000"
    depends_on:
      - storage_api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge